/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIdRouteImport } from './routes/research.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminResearchRouteImport } from './routes/admin.research'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminResearchTemplatesRouteImport } from './routes/admin.research.templates'
import { Route as AdminResearchNewRouteImport } from './routes/admin.research.new'
import { Route as AdminActivePeriodRouteImport } from './routes/admin.active.$period'
import { Route as AdminResearchEditIdRouteImport } from './routes/admin.research.edit.$id'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResearchRoute = AdminResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminResearchTemplatesRoute = AdminResearchTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminResearchRoute,
} as any)
const AdminResearchNewRoute = AdminResearchNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminResearchRoute,
} as any)
const AdminActivePeriodRoute = AdminActivePeriodRouteImport.update({
  id: '/active/$period',
  path: '/active/$period',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResearchEditIdRoute = AdminResearchEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/research': typeof AdminResearchRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/research/$id': typeof ResearchIdRoute
  '/admin/active/$period': typeof AdminActivePeriodRoute
  '/admin/research/new': typeof AdminResearchNewRoute
  '/admin/research/templates': typeof AdminResearchTemplatesRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/research/edit/$id': typeof AdminResearchEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/research': typeof AdminResearchRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/research/$id': typeof ResearchIdRoute
  '/admin/active/$period': typeof AdminActivePeriodRoute
  '/admin/research/new': typeof AdminResearchNewRoute
  '/admin/research/templates': typeof AdminResearchTemplatesRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/research/edit/$id': typeof AdminResearchEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/research': typeof AdminResearchRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/research/$id': typeof ResearchIdRoute
  '/admin/active/$period': typeof AdminActivePeriodRoute
  '/admin/research/new': typeof AdminResearchNewRoute
  '/admin/research/templates': typeof AdminResearchTemplatesRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/research/edit/$id': typeof AdminResearchEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/profile'
    | '/saved'
    | '/admin/chat'
    | '/admin/diagnostics'
    | '/admin/research'
    | '/admin/users'
    | '/research/$id'
    | '/admin/active/$period'
    | '/admin/research/new'
    | '/admin/research/templates'
    | '/admin/users/$userId'
    | '/admin/research/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/profile'
    | '/saved'
    | '/admin/chat'
    | '/admin/diagnostics'
    | '/admin/research'
    | '/admin/users'
    | '/research/$id'
    | '/admin/active/$period'
    | '/admin/research/new'
    | '/admin/research/templates'
    | '/admin/users/$userId'
    | '/admin/research/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/profile'
    | '/saved'
    | '/admin/chat'
    | '/admin/diagnostics'
    | '/admin/research'
    | '/admin/users'
    | '/research/$id'
    | '/admin/active/$period'
    | '/admin/research/new'
    | '/admin/research/templates'
    | '/admin/users/$userId'
    | '/admin/research/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  ResearchIdRoute: typeof ResearchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/research': {
      id: '/admin/research'
      path: '/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof AdminResearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/research/templates': {
      id: '/admin/research/templates'
      path: '/templates'
      fullPath: '/admin/research/templates'
      preLoaderRoute: typeof AdminResearchTemplatesRouteImport
      parentRoute: typeof AdminResearchRoute
    }
    '/admin/research/new': {
      id: '/admin/research/new'
      path: '/new'
      fullPath: '/admin/research/new'
      preLoaderRoute: typeof AdminResearchNewRouteImport
      parentRoute: typeof AdminResearchRoute
    }
    '/admin/active/$period': {
      id: '/admin/active/$period'
      path: '/active/$period'
      fullPath: '/admin/active/$period'
      preLoaderRoute: typeof AdminActivePeriodRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/research/edit/$id': {
      id: '/admin/research/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/research/edit/$id'
      preLoaderRoute: typeof AdminResearchEditIdRouteImport
      parentRoute: typeof AdminResearchRoute
    }
  }
}

interface AdminResearchRouteChildren {
  AdminResearchNewRoute: typeof AdminResearchNewRoute
  AdminResearchTemplatesRoute: typeof AdminResearchTemplatesRoute
  AdminResearchEditIdRoute: typeof AdminResearchEditIdRoute
}

const AdminResearchRouteChildren: AdminResearchRouteChildren = {
  AdminResearchNewRoute: AdminResearchNewRoute,
  AdminResearchTemplatesRoute: AdminResearchTemplatesRoute,
  AdminResearchEditIdRoute: AdminResearchEditIdRoute,
}

const AdminResearchRouteWithChildren = AdminResearchRoute._addFileChildren(
  AdminResearchRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminResearchRoute: typeof AdminResearchRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminActivePeriodRoute: typeof AdminActivePeriodRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminResearchRoute: AdminResearchRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminActivePeriodRoute: AdminActivePeriodRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  ResearchIdRoute: ResearchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
